/*
 e-Approval / e-Appraisal — DDL for PostgreSQL
 Generated: 2026-03-01
 Notes:
   - Run database creation step first as a privileged user.
   - Then connect to database eappraisal and execute this script.
*/

-- =============================================
-- 0) DATABASE (run manually if not already created)
-- =============================================
-- CREATE DATABASE eappraisal;
-- \c eappraisal

-- =============================================
-- 1) SCHEMA
-- =============================================
CREATE SCHEMA IF NOT EXISTS apps;

-- =============================================
-- 2) REFERENCE TABLES
-- =============================================
CREATE TABLE IF NOT EXISTS apps.ref_rating_scale (
  scale_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(120) NOT NULL,
  min_score      NUMERIC(6,3) NOT NULL,
  max_score      NUMERIC(6,3) NOT NULL,
  step           NUMERIC(6,3) NOT NULL,
  CONSTRAINT ck_ref_rating_scale_range CHECK (max_score > min_score AND step > 0)
);

CREATE TABLE IF NOT EXISTS apps.ref_stage (
  code           VARCHAR(16)  NOT NULL PRIMARY KEY,
  name           VARCHAR(120) NOT NULL,
  order_no       INT NOT NULL,
  is_final       BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS apps.ref_visibility (
  code           VARCHAR(10) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS apps.ref_currency (
  code           CHAR(3) NOT NULL PRIMARY KEY
);

-- =============================================
-- 3) ORG & SECURITY
-- =============================================
CREATE TABLE IF NOT EXISTS apps.org_unit (
  org_unit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(200) NOT NULL,
  path           VARCHAR(400) NOT NULL UNIQUE,
  cost_center    VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS apps."user" (
  user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  given_name       VARCHAR(100) NOT NULL,
  family_name      VARCHAR(100) NOT NULL,
  work_email       VARCHAR(256) NOT NULL UNIQUE,
  password         VARCHAR(255) NULL,
  employee_code    VARCHAR(50) NULL,
  status           VARCHAR(16) NOT NULL CHECK (status IN ('Active','Inactive')),
  locale           VARCHAR(16) NULL,
  time_zone        VARCHAR(64) NULL,
  address          VARCHAR(255) NULL,
  city             VARCHAR(100) NULL,
  phone            VARCHAR(20) NULL,
  mobile           VARCHAR(20) NULL,
  dob              DATE NULL,
  gender           VARCHAR(16) NULL,
  marital_status   VARCHAR(20) NULL,
  doj              DATE NULL,
  passport         VARCHAR(32) NULL,
  pan              VARCHAR(32) NULL,
  work_experience  INT NULL,
  reports_to_id    BIGINT NULL,
  org_unit_id      BIGINT NOT NULL,
  created_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by       BIGINT NULL,
  updated_at       TIMESTAMP(3) NULL,
  updated_by       BIGINT NULL,
  CONSTRAINT fk_user_org_unit FOREIGN KEY (org_unit_id) REFERENCES apps.org_unit(org_unit_id),
  CONSTRAINT fk_user_reports_to FOREIGN KEY (reports_to_id) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_user_org ON apps."user"(org_unit_id);

CREATE TABLE IF NOT EXISTS apps.user_manager (
  user_id        BIGINT NOT NULL,
  manager_id     BIGINT NOT NULL,
  effective_from TIMESTAMP(3) NOT NULL,
  effective_to   TIMESTAMP(3) NULL,
  CONSTRAINT pk_user_manager PRIMARY KEY (user_id, effective_from),
  CONSTRAINT fk_um_user     FOREIGN KEY (user_id)    REFERENCES apps."user"(user_id),
  CONSTRAINT fk_um_manager  FOREIGN KEY (manager_id) REFERENCES apps."user"(user_id)
);

CREATE TABLE IF NOT EXISTS apps.role (
  role_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(100) NOT NULL UNIQUE,
  description    VARCHAR(400) NULL
);

CREATE TABLE IF NOT EXISTS apps.permission (
  permission_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(150) NOT NULL UNIQUE,
  scope          VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS apps.user_role (
  user_id        BIGINT NOT NULL,
  role_id        BIGINT NOT NULL,
  effective_from TIMESTAMP(3) NOT NULL,
  effective_to   TIMESTAMP(3) NULL,
  CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id, effective_from),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES apps."user"(user_id),
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES apps.role(role_id)
);

CREATE TABLE IF NOT EXISTS apps.role_permission (
  role_id        BIGINT NOT NULL,
  permission_id  BIGINT NOT NULL,
  CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES apps.role(role_id),
  CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES apps.permission(permission_id)
);

-- =============================================
-- 4) APPRAISAL CORE
-- =============================================
CREATE TABLE IF NOT EXISTS apps.appraisal_cycle (
  cycle_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(120) NOT NULL,
  start_date       DATE NOT NULL,
  end_date         DATE NOT NULL,
  state            VARCHAR(16) NOT NULL CHECK (state IN ('Open','Frozen','Closed')),
  policy_version   VARCHAR(50) NULL,
  rating_scale_id  BIGINT NULL,
  created_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by       BIGINT NULL,
  updated_at       TIMESTAMP(3) NULL,
  updated_by       BIGINT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cycle_name ON apps.appraisal_cycle(name);

CREATE TABLE IF NOT EXISTS apps.appraisal (
  appraisal_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id          BIGINT NOT NULL,
  subject_user_id   BIGINT NOT NULL,
  manager_user_id   BIGINT NOT NULL,
  status            VARCHAR(16) NOT NULL CHECK (status IN ('Draft','InReview','Final')),
  overall_rating    NUMERIC(5,2) NULL,
  finalised_at      TIMESTAMP(3) NULL,
  locked_until      TIMESTAMP(3) NULL,
  created_at        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by        BIGINT NULL,
  updated_at        TIMESTAMP(3) NULL,
  updated_by        BIGINT NULL,
  CONSTRAINT fk_appraisal_cycle   FOREIGN KEY (cycle_id)        REFERENCES apps.appraisal_cycle(cycle_id),
  CONSTRAINT fk_appraisal_subject FOREIGN KEY (subject_user_id) REFERENCES apps."user"(user_id),
  CONSTRAINT fk_appraisal_manager FOREIGN KEY (manager_user_id) REFERENCES apps."user"(user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_appraisal_subject_cycle ON apps.appraisal(subject_user_id, cycle_id);
CREATE INDEX IF NOT EXISTS ix_appraisal_cycle ON apps.appraisal(cycle_id);

CREATE TABLE IF NOT EXISTS apps.objective (
  objective_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appraisal_id   BIGINT NOT NULL,
  title          VARCHAR(200) NOT NULL,
  description    TEXT NULL,
  weight         NUMERIC(5,2) NULL,
  CONSTRAINT fk_objective_appraisal FOREIGN KEY (appraisal_id) REFERENCES apps.appraisal(appraisal_id)
);

CREATE INDEX IF NOT EXISTS ix_objective_appraisal ON apps.objective(appraisal_id);

CREATE TABLE IF NOT EXISTS apps.evidence (
  evidence_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  objective_id   BIGINT NOT NULL,
  file_name      VARCHAR(260) NOT NULL,
  storage_uri    VARCHAR(1024) NOT NULL,
  mime_type      VARCHAR(100) NOT NULL,
  size_bytes     BIGINT NOT NULL,
  uploaded_at    TIMESTAMP(3) NOT NULL,
  CONSTRAINT fk_evidence_objective FOREIGN KEY (objective_id) REFERENCES apps.objective(objective_id)
);

CREATE INDEX IF NOT EXISTS ix_evidence_objective ON apps.evidence(objective_id);

CREATE TABLE IF NOT EXISTS apps.comment (
  comment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appraisal_id    BIGINT NOT NULL,
  author_user_id  BIGINT NOT NULL,
  visibility      VARCHAR(10) NOT NULL CHECK (visibility IN ('Mgr','HR','All')),
  body            TEXT NOT NULL,
  created_at      TIMESTAMP(3) NOT NULL,
  CONSTRAINT fk_comment_appraisal FOREIGN KEY (appraisal_id) REFERENCES apps.appraisal(appraisal_id),
  CONSTRAINT fk_comment_author    FOREIGN KEY (author_user_id) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_comment_appraisal ON apps.comment(appraisal_id, created_at);

CREATE TABLE IF NOT EXISTS apps.rating (
  rating_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appraisal_id    BIGINT NOT NULL,
  dimension       VARCHAR(100) NOT NULL,
  score           NUMERIC(6,3) NOT NULL,
  scale           NUMERIC(6,3) NULL,
  rater_user_id   BIGINT NOT NULL,
  created_at      TIMESTAMP(3) NOT NULL,
  CONSTRAINT fk_rating_appraisal FOREIGN KEY (appraisal_id) REFERENCES apps.appraisal(appraisal_id),
  CONSTRAINT fk_rating_rater     FOREIGN KEY (rater_user_id) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_rating_appraisal ON apps.rating(appraisal_id);

CREATE TABLE IF NOT EXISTS apps.stage_history (
  stage_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appraisal_id    BIGINT NOT NULL,
  from_stage      VARCHAR(16) NOT NULL,
  to_stage        VARCHAR(16) NOT NULL,
  changed_by      BIGINT NOT NULL,
  changed_at      TIMESTAMP(3) NOT NULL,
  reason          VARCHAR(400) NULL,
  CONSTRAINT fk_stage_appraisal  FOREIGN KEY (appraisal_id) REFERENCES apps.appraisal(appraisal_id),
  CONSTRAINT fk_stage_changed_by FOREIGN KEY (changed_by)   REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_stage_appraisal ON apps.stage_history(appraisal_id, changed_at);

CREATE TABLE IF NOT EXISTS apps.ctc_snapshot (
  ctc_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appraisal_id      BIGINT NOT NULL,
  approver_user_id  BIGINT NOT NULL,
  currency          CHAR(3) NOT NULL,
  components_json   TEXT NOT NULL,
  approved_at       TIMESTAMP(3) NOT NULL,
  CONSTRAINT fk_ctc_appraisal FOREIGN KEY (appraisal_id) REFERENCES apps.appraisal(appraisal_id),
  CONSTRAINT fk_ctc_approver  FOREIGN KEY (approver_user_id) REFERENCES apps."user"(user_id),
  CONSTRAINT fk_ctc_currency  FOREIGN KEY (currency) REFERENCES apps.ref_currency(code)
);

CREATE INDEX IF NOT EXISTS ix_ctc_appraisal ON apps.ctc_snapshot(appraisal_id);

CREATE TABLE IF NOT EXISTS apps.unlock_request (
  unlock_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appraisal_id   BIGINT NOT NULL,
  raised_by      BIGINT NOT NULL,
  reason         VARCHAR(500) NOT NULL,
  status         VARCHAR(12) NOT NULL CHECK (status IN ('Pending','Approved','Rejected')),
  processed_by   BIGINT NULL,
  processed_at   TIMESTAMP(3) NULL,
  created_at     TIMESTAMP(3) NOT NULL,
  CONSTRAINT fk_unlock_appraisal FOREIGN KEY (appraisal_id) REFERENCES apps.appraisal(appraisal_id),
  CONSTRAINT fk_unlock_raiser    FOREIGN KEY (raised_by)    REFERENCES apps."user"(user_id),
  CONSTRAINT fk_unlock_processor FOREIGN KEY (processed_by) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_unlock_appraisal ON apps.unlock_request(appraisal_id, created_at);

-- =============================================
-- 5) OUTBOX / EXPORTS / AUDIT
-- =============================================
CREATE TABLE IF NOT EXISTS apps.notification (
  notification_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id  BIGINT NOT NULL,
  topic              VARCHAR(120) NOT NULL,
  payload_json       TEXT NOT NULL,
  status             VARCHAR(10) NOT NULL CHECK (status IN ('Queued','Sent','Failed')),
  about_appraisal_id BIGINT NULL,
  retry_count        INT NOT NULL DEFAULT 0,
  created_at         TIMESTAMP(3) NOT NULL,
  sent_at            TIMESTAMP(3) NULL,
  CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_user_id) REFERENCES apps."user"(user_id),
  CONSTRAINT fk_notification_appraisal FOREIGN KEY (about_appraisal_id) REFERENCES apps.appraisal(appraisal_id)
);

CREATE INDEX IF NOT EXISTS ix_notification_status ON apps.notification(status, created_at);
CREATE INDEX IF NOT EXISTS ix_notification_recipient ON apps.notification(recipient_user_id, status);

CREATE TABLE IF NOT EXISTS apps.export_job (
  export_job_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id        BIGINT NOT NULL,
  format          VARCHAR(8) NOT NULL CHECK (format IN ('CSV','XLSX','JSON')),
  filter_json     TEXT NULL,
  created_by      BIGINT NOT NULL,
  created_at      TIMESTAMP(3) NOT NULL,
  completed_at    TIMESTAMP(3) NULL,
  storage_uri     VARCHAR(1024) NULL,
  CONSTRAINT fk_export_cycle   FOREIGN KEY (cycle_id) REFERENCES apps.appraisal_cycle(cycle_id),
  CONSTRAINT fk_export_creator FOREIGN KEY (created_by) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_export_cycle ON apps.export_job(cycle_id, created_at DESC);

CREATE TABLE IF NOT EXISTS apps.audit_event (
  audit_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id    BIGINT NULL,
  entity_type      VARCHAR(24) NOT NULL,
  entity_id        BIGINT NOT NULL,
  action           VARCHAR(24) NOT NULL,
  "at"            TIMESTAMP(3) NOT NULL,
  ip_hash          BYTEA NULL,
  user_agent_hash  BYTEA NULL,
  details_json     TEXT NULL,
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_audit_entity ON apps.audit_event(entity_type, entity_id, "at");
CREATE INDEX IF NOT EXISTS ix_audit_actor  ON apps.audit_event(actor_user_id, "at");

-- =============================================
-- 6) OPTIONAL VIEWS
-- =============================================
CREATE OR REPLACE VIEW apps.vw_appraisal_summary AS
SELECT a.appraisal_id, a.cycle_id, a.subject_user_id, a.manager_user_id,
       a.status, a.overall_rating, a.finalised_at
FROM apps.appraisal a;

CREATE OR REPLACE VIEW apps.vw_ctc_secure AS
SELECT c.ctc_id, c.appraisal_id, c.currency, c.approved_at
FROM apps.ctc_snapshot c;

-- =============================================
-- 7) SESSION / TOKEN MANAGEMENT
-- =============================================
CREATE TABLE IF NOT EXISTS apps.session_token (
  session_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  token           VARCHAR(512) NOT NULL,
  issued_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at      TIMESTAMP(3) NOT NULL,
  ip_address      VARCHAR(64) NULL,
  user_agent      VARCHAR(256) NULL,
  revoked         BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at      TIMESTAMP(3) NULL,
  CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_session_user ON apps.session_token(user_id, expires_at);

CREATE TABLE IF NOT EXISTS apps.refresh_token (
  refresh_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  token           VARCHAR(512) NOT NULL,
  issued_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at      TIMESTAMP(3) NOT NULL,
  ip_address      VARCHAR(64) NULL,
  user_agent      VARCHAR(256) NULL,
  revoked         BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at      TIMESTAMP(3) NULL,
  CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES apps."user"(user_id)
);

CREATE INDEX IF NOT EXISTS ix_refresh_user ON apps.refresh_token(user_id, expires_at);
